### ISSUE TITLE
XXX Instance UID

### ISSUE THREAD

**Issue by Imartinezzalacain** [navalpablo/dicom_sorting_toolkit#1]
Must be all numbers, and the random seed gives also letters. 

Study Instance UID Attribute
Tag	(0020,000D)
Type	Required (1)
Keyword	StudyInstanceUID
Value Multiplicity	1
Value Representation	Unique Identifier (UI)

https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_6.2.html

**Comment by navalpablo** [comment]
Thx solved!
